version: '3'

services:
  springboot:
    build: .
    container_name: springboot-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=America/Vancouver
    networks:
      - my-network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "8090:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=techassist
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    networks:
      - my-network

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    depends_on:
      - springboot
      - mysql
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

  #  unnecessary for development on local environment
  #  coturn:
  #    image: instrumentisto/coturn
  #    restart: always
  #    environment:
  #      - TURN_PUBLIC_IP=<IP_ADDRESS>
  #      - TURN_REALM=username
  #      - TURN_SECRET=password
  #    ports:
  #      - "3478:3478/udp"
  #      - "3478:3478/tcp"
  #      - "65435-65535:65435-65535/udp"